### ISSUE TITLE
custom Graphite path prefix in nagios_perfdata.rb

### ISSUE THREAD

**Issue by cruschke** [portertech/chef-monitor#22]
Some users store their Graphite metrics to live.servers.myhost.mycheck, others in servers.live.myhost.mycheck etc ... So supporting a customizable path prefix would be really appriciated.

As an additional requirement this "live" is set in client[:environment] in the Sensu client config.

**Comment by portertech** [comment]
@cruschke Please create an issue or submit a pull-request to get this functionality in the Mutator, the correct repository to do this is https://github.com/sensu/sensu-community-plugins We can then pull it into this cookbook.
