### ISSUE TITLE
Remove dashboard_service

### ISSUE THREAD

**Issue by Afterglow** [portertech/chef-monitor#23]
The sensu cookbook doesn't appear to include the sensu::dashboard_service recipe included in master.rb anymore, it probably needs to be removed or replaced with some other thing?

**Comment by larryg-sg** [comment]
It looks like the dashboard_service recipe was dropped because Sensu 0.13.1 stopped including a dashboard. The docs now recommend using [Uchiwa](http://sensuapp.org/docs/latest/dashboards_uchiwa). Fortunately, there is already a Chef cookbook for that…

**Comment by sethlindberg** [comment]
I've submitted a pull request for a fix, but haven't done a lot of testing.  it's just a quick and dirty replace sensu::dashboard_service with uchiwa.  You can check it out here:

https://github.com/sethlindberg/chef-monitor/tree/remove_dash

**Comment by portertech** [comment]
Change merged. Using Uchiwa.
