### ISSUE TITLE
rabbitmq management port is wrong

### ISSUE THREAD

**Issue by runningman84** [portertech/chef-monitor#29]
Please update this check from here:
https://github.com/sensu/sensu-community-plugins/blob/master/plugins/rabbitmq/rabbitmq-overview-metrics.rb

The default rabbitmq management api port ist 15672.

**Comment by runningman84** [comment]
someone has already fixed this issue in his fork:
https://github.com/bfraser/chef-monitor/commit/b1ef0f1f9925ebf14adb95d5515cd6fb3963d2b3

**Comment by portertech** [comment]
Updated the plugin, thank you for reporting :+1:
